name: run unit tests

on:
  pull_request:
    branches:
      - main

jobs:
  run_unit_tests:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install the dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the unit tests
        run: |
          python manage.py test --no-input --timing
